export const CLASS_NAME = "TEMP HELPERS =>";

export const LOG_LEVES = {
  NO_LOG: -2,
  ERRORS: -1,
  WARNS: 0,
  BASIC: 1,
  DETAILED: 2,
  VARIABLES: 3,
};

export const FUNCTIONS_NAMES = {
  RETRIEVE_TEMP_VALUE_TIME_ARRAY: "RETRIEVE_TEMP_VALUE_TIME_ARRAY: =>",
};

export const FUNCTION_LOG_LEVEL = {
  RETRIEVE_TEMP_VALUE_TIME_ARRAY: LOG_LEVES.VARIABLES,
};
